### ISSUE TITLE
Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by be4i** [adeotek/DotNet.SqlDependencyListener#6]
Hello @adeotek , first I want to say thank you for this very simple but effective lib.
Is there a reason why you use the old System.Data.SqlClient and not the new one Microsoft.Data.SqlClient ?
Do you think we can upgrade ?

**Comment by adeotek** [comment]
Hi @be4i, thank you for the interest in this library. I will look into it and try to upgrade it.

**Comment by adeotek** [comment]
Hi @be4i, I was thinking of migrating from `netstandard2.0` to `net6.0`. Would this be a problem for you?

**Comment by be4i** [comment]
Hey @adeotek, not really but I think is good idea to target .net standard 2.0 bc then it can be used in the full .net framework.Maybe should target both ?

**Comment by adeotek** [comment]
Hi @be4i, I have published a new version (1.0.4) with the SqlClient migrated from System.Data.SqlClient to Microsoft.Data.SqlClient. Also, I kept the target as `netstandard2.0`.

Please let me know if you encounter any issues.
